{
 "title": "IPFS Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"ipfs\", instance=~\"ipfs:5001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (ipfs_p2p_peers_total{job=~\"ipfs\", instance=~\"ipfs:5001\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of peerings",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(transport) (ipfs_p2p_peers_total{instance=~\"ipfs:5001\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"ipfs\", instance=~\"ipfs:5001\"}"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"ipfs\", instance=~\"ipfs:5001\"}[5m]) * 1000"
    }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"ipfs\", instance=~\"ipfs:5001\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"ipfs\", instance=~\"ipfs:5001\"}"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "irate(go_gc_duration_seconds_sum{job=~\"ipfs\", instance=~\"ipfs:5001\"}[1m])"
    }
   ]
  }
 ]
}