{
 "title": "Keycloak Metrics Dashboard",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPI\r\n\r\nhttps://github.com/aerogear/keycloak-metrics-spi",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\"})*100/sum(jvm_memory_bytes_max{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_bytes_max)", "legendFormat": "Max" },
    {
     "expr": "sum(jvm_memory_bytes_committed)",
     "legendFormat": "Comitted"
    },
    { "expr": "sum(jvm_memory_bytes_used)", "legendFormat": "Used" }
   ]
  },
  {
   "title": "4xx and 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(increase(keycloak_response_errors[30m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request duration method = \"GET\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket{method=\"GET\"}[30m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"GET\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{method=\"GET\", le=\"100.0\"}[30m])) / sum(rate(keycloak_request_duration_count{method=\"GET\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"POST\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket{method=\"POST\"}[30m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"POST\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{method=\"POST\", le=\"100.0\"}[30m])) / sum(rate(keycloak_request_duration_count{method=\"POST\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"HEAD\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket{method=\"HEAD\"}[30m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"HEAD\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{method=\"HEAD\", le=\"100.0\"}[30m])) / sum(rate(keycloak_request_duration_count{method=\"HEAD\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Request duration method = \"PUT\" Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(keycloak_request_duration_bucket{method=\"PUT\"}[30m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentage of requests \"PUT\"  method  was served in 100ms or below",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(keycloak_request_duration_bucket{method=\"PUT\", le=\"100.0\"}[30m])) / sum(rate(keycloak_request_duration_count{method=\"PUT\"}[30m])) * 100"
    }
   ]
  }
 ]
}