{
 "title": "SugarFunge Node Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_block_height", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Network bytes total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of network gossip peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  }
 ]
}